apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels: 
    volume-target: jenkins-disk
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /jenkins_home
