apiVersion: v1
kind: Pod
metadata:
  name: jenkins-container-test
spec:
  containers:
  - name: jenkins-container-test
    image: nginx
    volumeMounts:
    - name: use-jenkins-pvc-volume
      mountPath: /jenkins_home
  volumes:
  - name: use-jenkins-pvc-volume
    persistentVolumeClaim:
      claimName: jenkins-pvc