apiVersion: v1
kind: Pod
metadata:
  name: use-pvc
spec:
  containers:
  - name: use-pvc-container
    image: nginx
    volumeMounts:
    - name: use-pvc-volume
      mountPath: /check_data
  volumes:
  - name: use-pvc-volume
    persistentVolumeClaim:
      claimName: my-pvc
