apiVersion: v1
kind: Pod
metadata:
  name: use-pvc-second
spec:
  containers:
  - name: use-pvc-second-container
    image: nginx
    volumeMounts:
    - name: use-pvc-volume
      mountPath: /data
  volumes:
  - name: use-pvc-volume
    persistentVolumeClaim:
      claimName: my-pvc
